"""Generate the 15 labeled test PDFs. Filenames use a NN_ prefix so they
sort by rule number (00 = the all-pass case, 01-14 = rule-specific cases).

Run from the repo root:
    venv/bin/python3.14 test_fixtures/_generate.py
"""
import os
import shutil
import fitz  # PyMuPDF

OUT = os.path.dirname(os.path.abspath(__file__))


def out(name: str) -> str:
    return os.path.join(OUT, name)


# -----------------------------------------------------------------------------
# Step 1: bring legacy filenames forward (idempotent — runs once)
# -----------------------------------------------------------------------------
LEGACY_RENAMES = {
    "fully_compliant_baseline.pdf": "00_all_rules_pass.pdf",
    "old_pdf_version_1_2.pdf": "01_pdf_version_old.pdf",
    "external_file_link_demo.pdf": "06_external_hyperlink.pdf",
    "non_embedded_font_subset.pdf": "09_non_embedded_font.pdf",
    "annotated_with_highlights.pdf": "12_with_annotations.pdf",
    "explicit_zoom_bookmarks.pdf": "08_explicit_zoom_bookmarks.pdf",
    "external_url_hyperlink.pdf": None,  # superseded by 06_external_hyperlink.pdf
    "image_only_scan.pdf": "13_image_only_scan.pdf",
    "insufficient_left_margin.pdf": "11_narrow_left_margin.pdf",
    "non_letter_page_size_a4.pdf": "10_a4_page_size.pdf",
    "not_linearized.pdf": "04_not_linearized.pdf",
    "password_protected.pdf": "03_password_protected.pdf",
    "wrong_initial_view_thumbs.pdf": "07_wrong_initial_view.pdf",
}
for old, new in LEGACY_RENAMES.items():
    src = out(old)
    if not os.path.exists(src):
        continue
    if new is None:
        os.remove(src)
        print(f"removed:  {old}")
    elif not os.path.exists(out(new)):
        os.rename(src, out(new))
        print(f"renamed:  {old} -> {new}")


# -----------------------------------------------------------------------------
# Helpers
# -----------------------------------------------------------------------------
PARAGRAPH = (
    "This is a synthetic eCTD PDF generated by the test harness. "
    "It contains enough body text to satisfy the text-searchability check. "
    "Each file in this folder isolates one validation rule for review."
)


def make_letter_text_doc(headline: str = "Synthetic eCTD test PDF") -> fitz.Document:
    doc = fitz.open()
    page = doc.new_page(width=612, height=792)
    page.insert_text((72, 90), headline, fontsize=14)
    page.insert_textbox(fitz.Rect(72, 110, 540, 300), PARAGRAPH, fontsize=11)
    return doc


# -----------------------------------------------------------------------------
# 02 — text under the 50-char threshold (PDF_002 FAIL, PDF_013 PASS)
# -----------------------------------------------------------------------------
def make_short_text_only():
    doc = fitz.open()
    page = doc.new_page(width=612, height=792)
    page.insert_text((72, 90), "Hi.", fontsize=14)  # 3 chars, well below 50
    doc.save(out("02_short_text_only.pdf"))
    doc.close()


# -----------------------------------------------------------------------------
# 05 — bookmark whose action is an external URI (PDF_005 FAIL)
# -----------------------------------------------------------------------------
def make_external_bookmark():
    doc = make_letter_text_doc("PDF_005 FAIL: bookmark points to an external URL")
    # Try the fitz set_toc API first; fall back to xref manipulation if needed.
    try:
        doc.set_toc([[1, "External link", -1, {"kind": fitz.LINK_URI, "uri": "https://example.com"}]])
        doc.save(out("05_external_bookmark.pdf"))
        doc.close()
        return
    except Exception:
        pass
    doc.set_toc([[1, "External link", 1]])
    cat = doc.pdf_catalog()
    outlines_ref = doc.xref_get_key(cat, "Outlines")[1]
    out_xref = int(outlines_ref.split()[0])
    first_ref = doc.xref_get_key(out_xref, "First")[1]
    first_xref = int(first_ref.split()[0])
    doc.xref_set_key(first_xref, "Dest", "null")
    doc.xref_set_key(first_xref, "A", "<< /S /URI /URI (https://example.com) >>")
    doc.save(out("05_external_bookmark.pdf"))
    doc.close()


# -----------------------------------------------------------------------------
# 06 — external hyperlink (URL) — fallback only when the legacy file is gone.
# -----------------------------------------------------------------------------
def make_external_url_hyperlink_fallback():
    target = out("06_external_hyperlink.pdf")
    if os.path.exists(target):
        return
    doc = make_letter_text_doc("PDF_006 FAIL: external URL hyperlink")
    page = doc[0]
    rect = fitz.Rect(72, 320, 300, 340)
    page.insert_text(rect.tl + (0, 12), "https://example.com", fontsize=12, color=(0, 0, 1))
    page.insert_link({"kind": fitz.LINK_URI, "uri": "https://example.com", "from": rect})
    doc.save(target)
    doc.close()


# -----------------------------------------------------------------------------
# Per-rule generators (always rebuild)
# -----------------------------------------------------------------------------
def make_password_protected():
    doc = make_letter_text_doc("PDF_003 FAIL: password protected (user_pw=userpass)")
    perm = int(fitz.PDF_PERM_ACCESSIBILITY | fitz.PDF_PERM_PRINT)
    doc.save(
        out("03_password_protected.pdf"),
        encryption=fitz.PDF_ENCRYPT_AES_256,
        owner_pw="ownerpass",
        user_pw="userpass",
        permissions=perm,
    )
    doc.close()


def make_not_linearized():
    doc = make_letter_text_doc("PDF_004 FAIL: not optimized for Fast Web View")
    doc.save(out("04_not_linearized.pdf"))
    doc.close()


def make_wrong_initial_view():
    doc = make_letter_text_doc("PDF_007 FAIL: PageMode set to /UseThumbs")
    cat = doc.pdf_catalog()
    doc.xref_set_key(cat, "PageMode", "/UseThumbs")
    doc.save(out("07_wrong_initial_view.pdf"))
    doc.close()


def make_explicit_zoom_bookmark():
    doc = fitz.open()
    for i in range(2):
        p = doc.new_page(width=612, height=792)
        p.insert_text((72, 90), f"PDF_008 FAIL: bookmark with explicit zoom — page {i+1}", fontsize=14)
        p.insert_textbox(fitz.Rect(72, 110, 540, 300), PARAGRAPH, fontsize=11)
    toc = [
        [1, "Page 1 (zoom 150%)", 1, {"kind": 1, "to": fitz.Point(0, 0), "zoom": 1.5}],
        [1, "Page 2 (zoom 100%)", 2, {"kind": 1, "to": fitz.Point(0, 0), "zoom": 1.0}],
    ]
    doc.set_toc(toc)
    doc.save(out("08_explicit_zoom_bookmarks.pdf"))
    doc.close()


def make_a4_page_size():
    doc = fitz.open()
    page = doc.new_page(width=595, height=842)  # A4 in points
    page.insert_text((72, 90), "PDF_010 INFORMATION: A4 page size (8.27 x 11.69 in)", fontsize=14)
    page.insert_textbox(fitz.Rect(72, 110, 520, 300), PARAGRAPH, fontsize=11)
    doc.save(out("10_a4_page_size.pdf"))
    doc.close()


def make_narrow_left_margin():
    doc = fitz.open()
    page = doc.new_page(width=612, height=792)
    page.insert_text((10, 90), "PDF_011 INFORMATION: text begins at the left edge", fontsize=14)
    page.insert_textbox(fitz.Rect(10, 110, 540, 300), PARAGRAPH, fontsize=11)
    doc.save(out("11_narrow_left_margin.pdf"))
    doc.close()


def make_with_annotations():
    doc = make_letter_text_doc("PDF_012 WARNING: highlight + sticky note annotations")
    page = doc[0]
    page.add_highlight_annot(fitz.Rect(72, 88, 540, 104))
    page.add_text_annot(fitz.Point(540, 110), "reviewer note")
    doc.save(out("12_with_annotations.pdf"))
    doc.close()


def make_image_only_scan():
    src = make_letter_text_doc("This page will be flattened to an image.")
    pix = src[0].get_pixmap(dpi=150)
    src.close()
    doc = fitz.open()
    page = doc.new_page(width=612, height=792)
    page.insert_image(fitz.Rect(0, 0, 612, 792), pixmap=pix)
    doc.save(out("13_image_only_scan.pdf"))
    doc.close()


def make_bad_filename_copy():
    """14 — content is fully compliant; only the FILENAME violates PDF_014."""
    src = out("00_all_rules_pass.pdf")
    if os.path.exists(src):
        shutil.copyfile(src, out("14_BAD-Filename.pdf"))


# -----------------------------------------------------------------------------
# Run all
# -----------------------------------------------------------------------------
if __name__ == "__main__":
    make_short_text_only()
    make_password_protected()
    make_not_linearized()
    make_external_bookmark()
    make_external_url_hyperlink_fallback()
    make_wrong_initial_view()
    make_explicit_zoom_bookmark()
    make_a4_page_size()
    make_narrow_left_margin()
    make_with_annotations()
    make_image_only_scan()
    make_bad_filename_copy()

    print("\nFinal test fixture set:")
    for f in sorted(os.listdir(OUT)):
        if f.lower().endswith(".pdf"):
            print(f"  {f}  ({os.path.getsize(out(f))} bytes)")
